# -*- coding: utf-8 -*-
"""image.apisaver 账号池自动导入配置。"""
from config.env_loader import apply_env_overrides

IMAGE_API_AUTO_IMPORT: bool = False
IMAGE_API_BASE: str = "http://127.0.0.1:3100"
IMAGE_API_AUTH_KEY: str = ""
IMAGE_API_TIMEOUT: int = 20

# 额度监控与自动注册。默认关闭，避免部署后意外提交任务。
IMAGE_API_MONITOR_ENABLED: bool = False
IMAGE_API_QUOTA_URL: str = ""
IMAGE_API_QUOTA_PATH: str = "/api/accounts"
IMAGE_API_QUOTA_THRESHOLD: float = 1.0
IMAGE_API_QUOTA_POLL_SECONDS: int = 60
IMAGE_API_AUTO_REGISTER: bool = False
IMAGE_API_REGISTER_COUNT: int = 1
IMAGE_API_REGISTER_WORKERS_MIN: int = 1
IMAGE_API_REGISTER_WORKERS_MAX: int = 4
IMAGE_API_CPU_IDLE_PERCENT: int = 35
IMAGE_API_CPU_BUSY_PERCENT: int = 80
IMAGE_API_TRIGGER_COOLDOWN_SECONDS: int = 900

# 定时查活并把成功查活得到的最新 AT 同步到 image 账号池。
IMAGE_API_LIVE_CHECK_ENABLED: bool = False
IMAGE_API_LIVE_CHECK_INTERVAL_SECONDS: int = 3600
IMAGE_API_LIVE_CHECK_BATCH_SIZE: int = 20
IMAGE_API_LIVE_CHECK_SYNC_IMAGE: bool = True
IMAGE_API_LIVE_CHECK_DELETE_FAILED: bool = False
IMAGE_API_LIVE_CHECK_DELETE_FAILURE_THRESHOLD: int = 2
IMAGE_API_MIDNIGHT_CLEANUP_ENABLED: bool = False
IMAGE_API_MIDNIGHT_CLEANUP_HOUR: int = 0

apply_env_overrides(globals(), {
    "IMAGE_API_AUTO_IMPORT": "bool",
    "IMAGE_API_BASE": "str",
    "IMAGE_API_AUTH_KEY": "str",
    "IMAGE_API_TIMEOUT": "int",
    "IMAGE_API_MONITOR_ENABLED": "bool",
    "IMAGE_API_QUOTA_URL": "str",
    "IMAGE_API_QUOTA_PATH": "str",
    "IMAGE_API_QUOTA_THRESHOLD": "float",
    "IMAGE_API_QUOTA_POLL_SECONDS": "int",
    "IMAGE_API_AUTO_REGISTER": "bool",
    "IMAGE_API_REGISTER_COUNT": "int",
    "IMAGE_API_REGISTER_WORKERS_MIN": "int",
    "IMAGE_API_REGISTER_WORKERS_MAX": "int",
    "IMAGE_API_CPU_IDLE_PERCENT": "int",
    "IMAGE_API_CPU_BUSY_PERCENT": "int",
    "IMAGE_API_TRIGGER_COOLDOWN_SECONDS": "int",
    "IMAGE_API_LIVE_CHECK_ENABLED": "bool",
    "IMAGE_API_LIVE_CHECK_INTERVAL_SECONDS": "int",
    "IMAGE_API_LIVE_CHECK_BATCH_SIZE": "int",
    "IMAGE_API_LIVE_CHECK_SYNC_IMAGE": "bool",
    "IMAGE_API_LIVE_CHECK_DELETE_FAILED": "bool",
    "IMAGE_API_LIVE_CHECK_DELETE_FAILURE_THRESHOLD": "int",
    "IMAGE_API_MIDNIGHT_CLEANUP_ENABLED": "bool",
    "IMAGE_API_MIDNIGHT_CLEANUP_HOUR": "int",
})
